### ISSUE TITLE
Nice job but....

### ISSUE THREAD

**Issue by ghost** [GBratsos/brackets-zurb-foundation#1]
- Add support for Foundation Icon Fonts 2
- Add support for SVG Social Icons
- Add support for Stencils

Link: http://foundation.zurb.com/icon-fonts.html

Ty!

**Comment by wgoolsby** [comment]
I wouldn't recommend adding Foundation Icon Fonts or Social Icons yet. These playground items have not yet been tested with Foundation 5. Once they've been extensively tested I'll add support and submit a pull request.

Stencils are for wire framing in Omnigraffle.

**Comment by GBratsos** [comment]
That's right, i agree with @wgoolsby . Let's keep it straight forward.
