### ISSUE TITLE
Blank meta name

### ISSUE THREAD

**Issue by badcat** [GBratsos/brackets-zurb-foundation#10]
Suggest changing line 7 in the html template from a blank meta name to description.

` <meta name="" content="">`

becomes...

` <meta name="description" content="">`

This then allows the W3C validation tools to validate the document without further edits from the user.

thanks.

**Comment by GBratsos** [comment]
Thanks for the suggeston @badcat ! I've updated the extension! :)

**Comment by badcat** [comment]
Thanks!
