### ISSUE TITLE
Lovely Job!! - Would be great to add Foundation 6 support

### ISSUE THREAD

**Issue by grantkemp** [GBratsos/brackets-zurb-foundation#3]
Well done on above. 

Would be great to get Foundation 6 support added at some stage.

**Comment by badcat** [comment]
@grantkemp @GBratsos I'm new to this but tried to create proper Pull Requests for this after updating to Foundation for Sites v 6.2.1

**Comment by grantkemp** [comment]
Looks like you got a pull request nailed 👍

**Comment by badcat** [comment]
@grantkemp I'm not sure about that.  Remember the last time the interwebs went down?  I did that with a single Git commit.  :)  In the meanwhile, this seems to work  https://github.com/badcat/brackets-zurb-foundation   So if @GBratsos will take the Pull Requests (assuming I did it correctly) then it'll get merged.

**Comment by GBratsos** [comment]
Guys you are awesome! This update was on my "TODO" list for long time!

I uploaded the extension and it's ready for use! Thanks again! :D

**Comment by grantkemp** [comment]
Haven't tested - but assume it will work perfectly! 
Win!
